// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: pb/pgcapture.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Change_Operation int32

const (
	Change_INSERT Change_Operation = 0
	Change_UPDATE Change_Operation = 1
	Change_DELETE Change_Operation = 2
)

// Enum value maps for Change_Operation.
var (
	Change_Operation_name = map[int32]string{
		0: "INSERT",
		1: "UPDATE",
		2: "DELETE",
	}
	Change_Operation_value = map[string]int32{
		"INSERT": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x Change_Operation) Enum() *Change_Operation {
	p := new(Change_Operation)
	*p = x
	return p
}

func (x Change_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Change_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_pgcapture_proto_enumTypes[0].Descriptor()
}

func (Change_Operation) Type() protoreflect.EnumType {
	return &file_pb_pgcapture_proto_enumTypes[0]
}

func (x Change_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Change_Operation.Descriptor instead.
func (Change_Operation) EnumDescriptor() ([]byte, []int) {
	return file_pb_pgcapture_proto_rawDescGZIP(), []int{3, 0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*Message_Begin
	//	*Message_Commit
	//	*Message_Change
	Type isMessage_Type `protobuf_oneof:"type"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pgcapture_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pgcapture_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pb_pgcapture_proto_rawDescGZIP(), []int{0}
}

func (m *Message) GetType() isMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Message) GetBegin() *Begin {
	if x, ok := x.GetType().(*Message_Begin); ok {
		return x.Begin
	}
	return nil
}

func (x *Message) GetCommit() *Commit {
	if x, ok := x.GetType().(*Message_Commit); ok {
		return x.Commit
	}
	return nil
}

func (x *Message) GetChange() *Change {
	if x, ok := x.GetType().(*Message_Change); ok {
		return x.Change
	}
	return nil
}

type isMessage_Type interface {
	isMessage_Type()
}

type Message_Begin struct {
	Begin *Begin `protobuf:"bytes,1,opt,name=begin,proto3,oneof"`
}

type Message_Commit struct {
	Commit *Commit `protobuf:"bytes,2,opt,name=commit,proto3,oneof"`
}

type Message_Change struct {
	Change *Change `protobuf:"bytes,3,opt,name=change,proto3,oneof"`
}

func (*Message_Begin) isMessage_Type() {}

func (*Message_Commit) isMessage_Type() {}

func (*Message_Change) isMessage_Type() {}

type Begin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FinalLsn   uint64 `protobuf:"varint,1,opt,name=final_lsn,json=finalLsn,proto3" json:"final_lsn,omitempty"`
	CommitTime uint64 `protobuf:"varint,2,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	RemoteXid  uint32 `protobuf:"varint,3,opt,name=remote_xid,json=remoteXid,proto3" json:"remote_xid,omitempty"`
}

func (x *Begin) Reset() {
	*x = Begin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pgcapture_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Begin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Begin) ProtoMessage() {}

func (x *Begin) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pgcapture_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Begin.ProtoReflect.Descriptor instead.
func (*Begin) Descriptor() ([]byte, []int) {
	return file_pb_pgcapture_proto_rawDescGZIP(), []int{1}
}

func (x *Begin) GetFinalLsn() uint64 {
	if x != nil {
		return x.FinalLsn
	}
	return 0
}

func (x *Begin) GetCommitTime() uint64 {
	if x != nil {
		return x.CommitTime
	}
	return 0
}

func (x *Begin) GetRemoteXid() uint32 {
	if x != nil {
		return x.RemoteXid
	}
	return 0
}

type Commit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitLsn  uint64 `protobuf:"varint,1,opt,name=commit_lsn,json=commitLsn,proto3" json:"commit_lsn,omitempty"`
	EndLsn     uint64 `protobuf:"varint,2,opt,name=end_lsn,json=endLsn,proto3" json:"end_lsn,omitempty"`
	CommitTime uint64 `protobuf:"varint,3,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
}

func (x *Commit) Reset() {
	*x = Commit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pgcapture_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pgcapture_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_pb_pgcapture_proto_rawDescGZIP(), []int{2}
}

func (x *Commit) GetCommitLsn() uint64 {
	if x != nil {
		return x.CommitLsn
	}
	return 0
}

func (x *Commit) GetEndLsn() uint64 {
	if x != nil {
		return x.EndLsn
	}
	return 0
}

func (x *Commit) GetCommitTime() uint64 {
	if x != nil {
		return x.CommitTime
	}
	return 0
}

type Change struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op        Change_Operation `protobuf:"varint,1,opt,name=op,proto3,enum=pgcapture.Change_Operation" json:"op,omitempty"`
	Namespace string           `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table     string           `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	NewTuple  []*Field         `protobuf:"bytes,4,rep,name=new_tuple,json=newTuple,proto3" json:"new_tuple,omitempty"`
	OldTuple  []*Field         `protobuf:"bytes,5,rep,name=old_tuple,json=oldTuple,proto3" json:"old_tuple,omitempty"`
}

func (x *Change) Reset() {
	*x = Change{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pgcapture_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pgcapture_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_pb_pgcapture_proto_rawDescGZIP(), []int{3}
}

func (x *Change) GetOp() Change_Operation {
	if x != nil {
		return x.Op
	}
	return Change_INSERT
}

func (x *Change) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Change) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *Change) GetNewTuple() []*Field {
	if x != nil {
		return x.NewTuple
	}
	return nil
}

func (x *Change) GetOldTuple() []*Field {
	if x != nil {
		return x.OldTuple
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Oid   uint32 `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`
	Datum []byte `protobuf:"bytes,3,opt,name=datum,proto3" json:"datum,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pgcapture_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pgcapture_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_pb_pgcapture_proto_rawDescGZIP(), []int{4}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetOid() uint32 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *Field) GetDatum() []byte {
	if x != nil {
		return x.Datum
	}
	return nil
}

var File_pb_pgcapture_proto protoreflect.FileDescriptor

var file_pb_pgcapture_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x70, 0x67, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x67, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x95, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x62,
	0x65, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x67, 0x63,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05,
	0x62, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x2b, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x67, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x67, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42,
	0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x64, 0x0a, 0x05, 0x42, 0x65, 0x67, 0x69, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x6c, 0x73, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x4c, 0x73, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x78, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x58, 0x69, 0x64, 0x22, 0x61, 0x0a,
	0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x5f, 0x6c, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x4c, 0x73, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x73,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x4c, 0x73, 0x6e, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0xf8, 0x01, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x02, 0x6f,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x67, 0x63, 0x61, 0x70, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x09,
	0x6e, 0x65, 0x77, 0x5f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x67, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x6f,
	0x6c, 0x64, 0x5f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x67, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x08, 0x6f, 0x6c, 0x64, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x22, 0x2f, 0x0a, 0x09, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x53, 0x45, 0x52,
	0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x22, 0x43, 0x0a, 0x05, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61,
	0x74, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x64, 0x61, 0x74, 0x75, 0x6d,
	0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x75, 0x65, 0x69, 0x61, 0x6e, 0x2f, 0x70, 0x67, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_pgcapture_proto_rawDescOnce sync.Once
	file_pb_pgcapture_proto_rawDescData = file_pb_pgcapture_proto_rawDesc
)

func file_pb_pgcapture_proto_rawDescGZIP() []byte {
	file_pb_pgcapture_proto_rawDescOnce.Do(func() {
		file_pb_pgcapture_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_pgcapture_proto_rawDescData)
	})
	return file_pb_pgcapture_proto_rawDescData
}

var file_pb_pgcapture_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_pgcapture_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_pgcapture_proto_goTypes = []interface{}{
	(Change_Operation)(0), // 0: pgcapture.Change.Operation
	(*Message)(nil),       // 1: pgcapture.Message
	(*Begin)(nil),         // 2: pgcapture.Begin
	(*Commit)(nil),        // 3: pgcapture.Commit
	(*Change)(nil),        // 4: pgcapture.Change
	(*Field)(nil),         // 5: pgcapture.Field
}
var file_pb_pgcapture_proto_depIdxs = []int32{
	2, // 0: pgcapture.Message.begin:type_name -> pgcapture.Begin
	3, // 1: pgcapture.Message.commit:type_name -> pgcapture.Commit
	4, // 2: pgcapture.Message.change:type_name -> pgcapture.Change
	0, // 3: pgcapture.Change.op:type_name -> pgcapture.Change.Operation
	5, // 4: pgcapture.Change.new_tuple:type_name -> pgcapture.Field
	5, // 5: pgcapture.Change.old_tuple:type_name -> pgcapture.Field
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pb_pgcapture_proto_init() }
func file_pb_pgcapture_proto_init() {
	if File_pb_pgcapture_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_pgcapture_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pgcapture_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Begin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pgcapture_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pgcapture_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Change); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pgcapture_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_pgcapture_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_Begin)(nil),
		(*Message_Commit)(nil),
		(*Message_Change)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_pgcapture_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_pgcapture_proto_goTypes,
		DependencyIndexes: file_pb_pgcapture_proto_depIdxs,
		EnumInfos:         file_pb_pgcapture_proto_enumTypes,
		MessageInfos:      file_pb_pgcapture_proto_msgTypes,
	}.Build()
	File_pb_pgcapture_proto = out.File
	file_pb_pgcapture_proto_rawDesc = nil
	file_pb_pgcapture_proto_goTypes = nil
	file_pb_pgcapture_proto_depIdxs = nil
}
